---
title: "When Are You Going To Die?: The Demographics of Mortality"
author: "Gabriel Cage-Sepeda & Samuel Utzinger"
date: "2026-02-04"
output: PDF
---


## Data & Idea

The Society of Actuaries (SOA) created a socioeconomic and demographic dataset at the county, state, and national level using statistics from the American Community Survey (ACS) and the U.S. Decennial Census. They focused on variables that are useful covariates to mortality, e.g. age, sex, and race, so that this dataset could be used in conjunction with mortality data. The Centers for Disease Control and Prevention (CDC) has data on mortality rates for many different parameters, e.g. multiple causes of death, underlying causes of death, and infant deaths. We would like to analyze mortality and the social determinants of health in the United States at the county level using the demographic data from the ACS and mortality data on multiple causes of death from the CDC.


## Problems & Goals

Our current goals are to model mortality while considering necessary covariates in order to properly predict future mortality rates for people who die of multiple causes. We want to be able to make accurate predictions on mortality rates for different socioeconomic classes in the short-term and long-term.